# Generated by Django 4.2.17 on 2025-10-16 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="titre")),
                ("message", models.TextField(verbose_name="message")),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("new_opportunity", "Nouvelle opportunité"),
                            ("deadline_reminder", "Rappel d'échéance"),
                            ("status_update", "Mise à jour de statut"),
                            ("application_update", "Mise à jour de candidature"),
                            ("system", "Notification système"),
                            ("message", "Message"),
                        ],
                        max_length=30,
                        verbose_name="type",
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="lue")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créée le"),
                ),
                (
                    "object_id",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="ID de l'objet",
                    ),
                ),
                ("link", models.URLField(blank=True, null=True, verbose_name="lien")),
                (
                    "extra_data",
                    models.JSONField(
                        blank=True, null=True, verbose_name="données supplémentaires"
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "notification",
                "verbose_name_plural": "notifications",
                "ordering": ["-created_at"],
            },
        ),
    ]
