# Generated by Django 6.0.3 on 2026-03-05 16:22

import apps.accounts.models.user
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(db_index=True, error_messages={'unique': 'Un utilisateur avec cette adresse e-mail existe déjà.'}, max_length=254, unique=True, verbose_name='adresse e-mail')),
                ('user_type', models.CharField(choices=[('student', 'Étudiant'), ('professional', 'Professionnel'), ('organization', 'Organisation'), ('admin', 'Administrateur')], db_index=True, default='student', max_length=20, verbose_name="type d'utilisateur")),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Numéro ivoirien valide requis (ex: +2250102030405)', regex='^\\+?225[0-9]{8,10}$')], verbose_name='numéro de téléphone')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=apps.accounts.models.user.profile_picture_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), apps.accounts.models.user.validate_file_size], verbose_name='photo de profil')),
                ('is_verified', models.BooleanField(default=False, verbose_name='email vérifié')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de mise à jour')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'utilisateur',
                'verbose_name_plural': 'utilisateurs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('abidjan', 'Abidjan'), ('bouake', 'Bouaké'), ('daloa', 'Daloa'), ('yamoussoukro', 'Yamoussoukro'), ('san_pedro', 'San-Pédro'), ('korhogo', 'Korhogo'), ('man', 'Man'), ('other', 'Autre ville')], default='abidjan', max_length=50, verbose_name='ville')),
                ('education_level', models.CharField(blank=True, choices=[('secondary', 'Secondaire'), ('bac', 'Baccalauréat'), ('bts', 'BTS/DUT'), ('license', 'Licence'), ('master', 'Master'), ('phd', 'Doctorat'), ('other', 'Autre')], max_length=20, null=True, verbose_name="niveau d'éducation")),
                ('field_of_study', models.CharField(blank=True, help_text='Ex: Informatique, Gestion, Médecine...', max_length=200, null=True, verbose_name="domaine d'étude")),
                ('institution', models.CharField(blank=True, max_length=200, null=True, verbose_name='établissement')),
                ('graduation_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='année de graduation')),
                ('skills', models.JSONField(blank=True, default=list, help_text="Liste de compétences: ['Python', 'Excel', 'Communication']", verbose_name='compétences')),
                ('interests', models.JSONField(blank=True, default=list, help_text="Domaines d'intérêt: ['Tech', 'Finance', 'Santé']", verbose_name="centres d'intérêt")),
                ('languages', models.JSONField(blank=True, default=list, help_text="Langues parlées: ['Français', 'Anglais']", verbose_name='langues')),
                ('cv', models.FileField(blank=True, null=True, upload_to=apps.accounts.models.user.cv_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx']), apps.accounts.models.user.validate_file_size], verbose_name='CV')),
                ('linkedin_url', models.URLField(blank=True, null=True, verbose_name='LinkedIn')),
                ('portfolio_url', models.URLField(blank=True, null=True, verbose_name='Portfolio')),
                ('bio', models.TextField(blank=True, help_text='Décrivez vos objectifs professionnels', null=True, verbose_name='biographie')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'profil',
                'verbose_name_plural': 'profils',
            },
        ),
    ]
