# Generated by Django 4.2.17 on 2025-10-16 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OpportunityCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="nom")),
                (
                    "slug",
                    models.SlugField(max_length=120, unique=True, verbose_name="slug"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="icône"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="est actif"),
                ),
            ],
            options={
                "verbose_name": "catégorie d'opportunité",
                "verbose_name_plural": "catégories d'opportunités",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="titre")),
                (
                    "slug",
                    models.SlugField(max_length=280, unique=True, verbose_name="slug"),
                ),
                ("description", models.TextField(verbose_name="description")),
                (
                    "opportunity_type",
                    models.CharField(
                        choices=[
                            ("scholarship", "Bourse"),
                            ("internship", "Stage"),
                            ("job", "Emploi"),
                            ("competition", "Concours"),
                            ("training", "Formation"),
                            ("event", "Événement"),
                            ("other", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="type d'opportunité",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créée le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="mise à jour le"),
                ),
                (
                    "publication_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date de publication"
                    ),
                ),
                (
                    "deadline",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date limite"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="lieu"
                    ),
                ),
                (
                    "is_remote",
                    models.BooleanField(default=False, verbose_name="à distance"),
                ),
                (
                    "organization",
                    models.CharField(
                        max_length=255, verbose_name="organisme/entreprise"
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, null=True, verbose_name="site web"),
                ),
                (
                    "application_link",
                    models.URLField(
                        blank=True, null=True, verbose_name="lien de candidature"
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="email de contact",
                    ),
                ),
                (
                    "requirements",
                    models.TextField(blank=True, null=True, verbose_name="prérequis"),
                ),
                (
                    "education_level",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="niveau d'éducation requis",
                    ),
                ),
                (
                    "compensation",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="rémunération/montant",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="XOF", max_length=10, verbose_name="devise"
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="tags"
                    ),
                ),
                (
                    "featured",
                    models.BooleanField(default=False, verbose_name="mise en avant"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("published", "Publiée"),
                            ("closed", "Clôturée"),
                            ("expired", "Expirée"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="statut",
                    ),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="nombre de vues"
                    ),
                ),
                (
                    "application_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="nombre de candidatures"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opportunities",
                        to="opportunities.opportunitycategory",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_opportunities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "opportunité",
                "verbose_name_plural": "opportunités",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserOpportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relation_type",
                    models.CharField(
                        choices=[
                            ("saved", "Sauvegardée"),
                            ("applied", "Postulée"),
                            ("viewed", "Consultée"),
                            ("shared", "Partagée"),
                        ],
                        max_length=20,
                        verbose_name="type de relation",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créée le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="mise à jour le"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="notes"),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="statut"
                    ),
                ),
                (
                    "opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_relations",
                        to="opportunities.opportunity",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_opportunities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "opportunité utilisateur",
                "verbose_name_plural": "opportunités utilisateur",
                "ordering": ["-created_at"],
                "unique_together": {("user", "opportunity", "relation_type")},
            },
        ),
    ]
