# Generated by Django 6.0.3 on 2026-03-05 16:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='icône')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
            ],
            options={
                'verbose_name': 'catégorie',
                'verbose_name_plural': 'catégories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OpportunitySource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('source_type', models.CharField(choices=[('website', 'Site web (scraping)'), ('partner', 'Partenaire'), ('manual', 'Saisie manuelle'), ('api', 'API externe')], default='manual', max_length=20, verbose_name='type')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='sources/', verbose_name='logo')),
                ('scrape_config', models.JSONField(blank=True, default=dict, help_text='Sélecteurs CSS, intervalles, etc.', verbose_name='configuration scraping')),
                ('last_scraped_at', models.DateTimeField(blank=True, null=True, verbose_name='dernier scraping')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'source',
                'verbose_name_plural': 'sources',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='titre')),
                ('slug', models.SlugField(max_length=280, unique=True, verbose_name='slug')),
                ('description', models.TextField(verbose_name='description')),
                ('opportunity_type', models.CharField(choices=[('scholarship', 'Bourse'), ('internship', 'Stage'), ('job', 'Emploi'), ('training', 'Formation'), ('competition', 'Concours'), ('event', 'Événement'), ('other', 'Autre')], db_index=True, max_length=20, verbose_name='type')),
                ('organization', models.CharField(max_length=255, verbose_name='organisme')),
                ('organization_logo', models.ImageField(blank=True, null=True, upload_to='organizations/', verbose_name='logo organisme')),
                ('website', models.URLField(blank=True, null=True, verbose_name='site web')),
                ('application_link', models.URLField(blank=True, null=True, verbose_name='lien de candidature')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email de contact')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='lieu')),
                ('is_remote', models.BooleanField(default=False, verbose_name='à distance')),
                ('publication_date', models.DateTimeField(blank=True, null=True, verbose_name='date de publication')),
                ('deadline', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='date limite')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='date de début')),
                ('education_level', models.CharField(choices=[('any', 'Tous niveaux'), ('bac', 'Baccalauréat'), ('bts', 'BTS/DUT'), ('license', 'Licence'), ('master', 'Master'), ('phd', 'Doctorat')], default='any', max_length=20, verbose_name='niveau requis')),
                ('skills_required', models.JSONField(blank=True, default=list, help_text="Liste de compétences: ['Python', 'Excel', ...]", verbose_name='compétences requises')),
                ('experience_years', models.PositiveIntegerField(default=0, help_text='0 = débutant accepté', verbose_name="années d'expérience")),
                ('requirements', models.TextField(blank=True, null=True, verbose_name='autres prérequis')),
                ('compensation', models.CharField(blank=True, max_length=255, null=True, verbose_name='rémunération/montant')),
                ('currency', models.CharField(default='XOF', max_length=10, verbose_name='devise')),
                ('external_id', models.CharField(blank=True, help_text='ID dans le système source (pour éviter les doublons)', max_length=255, null=True, verbose_name='ID externe')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publiée'), ('closed', 'Clôturée'), ('expired', 'Expirée')], db_index=True, default='draft', max_length=20, verbose_name='statut')),
                ('featured', models.BooleanField(default=False, verbose_name='mise en avant')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='vues')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_opportunities', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='opportunities.opportunitycategory', verbose_name='catégorie')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='opportunities.opportunitysource', verbose_name='source')),
            ],
            options={
                'verbose_name': 'opportunité',
                'verbose_name_plural': 'opportunités',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('discovered', 'Découverte'), ('saved', 'Sauvegardée'), ('preparing', 'En préparation'), ('applied', 'Candidature envoyée'), ('interviewing', 'En entretien'), ('offer', 'Offre reçue'), ('accepted', 'Acceptée'), ('rejected', 'Refusée'), ('withdrawn', 'Retirée')], db_index=True, default='discovered', max_length=20, verbose_name='statut')),
                ('ai_match_score', models.FloatField(blank=True, help_text="Score 0-100 calculé par l'IA", null=True, verbose_name='score de matching')),
                ('ai_match_reasons', models.JSONField(blank=True, default=list, verbose_name='raisons du matching')),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('saved_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('status_updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes personnelles')),
                ('next_action', models.CharField(blank=True, max_length=255, null=True, verbose_name='prochaine action')),
                ('next_action_date', models.DateField(blank=True, null=True, verbose_name='date prochaine action')),
                ('cv_used', models.FileField(blank=True, null=True, upload_to='applications/cv/', verbose_name='CV utilisé')),
                ('cover_letter', models.FileField(blank=True, null=True, upload_to='applications/letters/', verbose_name='lettre de motivation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='opportunities.opportunity')),
            ],
            options={
                'verbose_name': 'candidature',
                'verbose_name_plural': 'candidatures',
                'ordering': ['-discovered_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='opportuniti_user_id_693c8a_idx'), models.Index(fields=['opportunity', 'status'], name='opportuniti_opportu_943e1b_idx')],
                'unique_together': {('user', 'opportunity')},
            },
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['status', 'deadline'], name='opportuniti_status_723867_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['opportunity_type', 'status'], name='opportuniti_opportu_f05940_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['source', 'external_id'], name='opportuniti_source__9f7a54_idx'),
        ),
    ]
